version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ
      - DEFAULT_DOMAIN=${SUB_DOMAIN}.${SERVER_DOMAIN}
      - IS_HTTPS_ENABLED=true
      # - GEOLITE_LICENSE_KEY=<GEOLITE_LICENSE_KEY>
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD
      - DB_HOST=database
    depends_on:
      - database
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.shlink.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.shlink.entrypoints: websecure
      traefik.http.services.shlink.loadbalancer.server.port: 8080

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.shlink-ui.rule: Host(`${SUB_DOMAIN_UI}.${SERVER_DOMAIN}`)
      traefik.http.routers.shlink-ui.entrypoints: websecure
      traefik.http.services.shlink-ui.loadbalancer.server.port: 80
      homepage.group: Infrastructure
      homepage.name: shlink
      homepage.icon: shlink
      homepage.href: https://${SUB_DOMAIN_UI}.${SERVER_DOMAIN}
      homepage.description: Link Shortener

  database:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

networks:
  traefik:
    name: zone1
    external: true
