version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    privileged: true
    env_file:
      - .env
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.dash.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.dash.entrypoints: websecure
      traefik.http.services.dash.loadbalancer.server.port: 3001
      traefik.http.routers.dash.middlewares: authelia@docker
      homepage.group: ${HOMEPAGE_GROUP}
      homepage.name: ${HOMEPAGE_NAME}
      homepage.icon: ${HOMEPAGE_ICON}
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: ${HOMEPAGE_DESCRIPTION}

networks:
  default:
    name: zone1
    external: true
