version: '3.6'
services:
  web:
    image: odoo:15.0
    depends_on:
      - mydb
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.odoo.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.odoo.entrypoints: websecure
      traefik.http.services.odoo.loadbalancer.server.port: 8069
      homepage.group: Media
      homepage.name: Odoo
      homepage.icon: odoo
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Odoo ERP und CRM

  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

networks:
  traefik:
    name: zone1
