version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.dozzle.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
      traefik.http.routers.dozzle.middlewares: authelia@docker
      homepage.group: Infrastructure
      homepage.name: Dozzle
      homepage.icon: dozzle
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Container logs

networks:
  traefik:
    name: zone1
    external: true
