version: "3"

services:
  vpncheckerVpn:
    image: ghcr.io/simonhaas/docker-vpn-checker:main
    restart: always
    network_mode: container:gluetun # see ../gluetun/docker-compose.yml

  vpncheckerNonvpn:
    image: ghcr.io/simonhaas/docker-vpn-checker:main
    restart: always
    networks:
      - traefik
    depends_on:
      - vpncheckerVpn
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.vpncheckerNonvpn.rule: Host(`vpnchecker-nonvpn.${SERVER_DOMAIN}`)
      traefik.http.routers.vpncheckerNonvpn.entrypoints: websecure
      traefik.http.services.vpncheckerNonvpn.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1
    external: true
