version: "3.6"
services:
    dolibarr:
        container_name: dolibarr
        image: monogramm/docker-dolibarr
        volumes: 
            - ./data/dolibarr/html:/var/www/html
            - ./dolibarr/docs:/var/www/documents
        environment: 
            - DOLI_AUTO_CONFIGURE=''
        restart: always
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=dolibarr"
            - "traefik.frontend.rule=Host:dolibarr.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"

    dolibarr-mariadb:
        image: mariadb
        container_name: "dolibarr-mariadb"
        hostname: dolibarr-mariadb
        networks:
            - traefik_proxy
        volumes:
            - ./data/mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=keinerweisdas
            - MYSQL_PASSWORD=mysql
            - MYSQL_DATABASE=dolibarr
            - MYSQL_USER=dolibarr

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge