version: "3.6"
services:
  bookstack_db:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/config
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    restart: unless-stopped

  bookstack:
    image: linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - APP_URL=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
    volumes:
      - ./data/app:/config
    depends_on:
      - bookstack_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.bookstack.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.bookstack.entrypoints: websecure
      traefik.http.services.bookstack.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1
