version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.nginxpm.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.nginxpm.entrypoints: websecure
      traefik.http.routers.nginxpm.service: nginxpm
      traefik.http.services.nginxpm.loadbalancer.server.port: 81
      
      traefik.http.routers.nginx80.rule: HostRegexp(`{${SERVER_DOMAIN}:.+}`)
      traefik.http.routers.nginx80.entrypoints: websecure
      traefik.http.routers.nginx80.priority: 1
      traefik.http.routers.nginx80.service: nginx80
      traefik.http.services.nginx80.loadbalancer.server.port: 80

      homepage.group: Infrastructure
      homepage.name: Nginx Proxy manager
      homepage.icon: nginx
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Nginx Proxy Manager

networks:
  traefik:
    name: zone1
    external: true
