version: "3.6"
services:
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: unless-stopped
    volumes:
    - ./data:/rainloop/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.rainloop.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.rainloop.entrypoints: websecure
      traefik.http.services.rainloop.loadbalancer.server.port: 8888
      homepage.group: Media
      homepage.name: Rainloop
      homepage.icon: rainloop
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Email client

networks:
  traefik:
    name: zone1
