version: "3.6"
services:
    rainloop:
        container_name: "rainloop"
        image: hardware/rainloop
        restart: always
        networks:
            - traefik_proxy
        volumes:
            - ../rainloop/data:/rainloop/data
        labels:
            - "traefik.backend=rainloop"
            - "traefik.frontend.rule=Host:rainloop.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=8888"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge