version: "3.6"
services:
    rainloop:
        image: hardware/rainloop
        container_name: rainloop
        restart: always
        networks: 
            - traefik
        security_opt:
            - no-new-privileges:true
        labels:
            - custom.network=private
            - "traefik.enable=true"
            - "traefik.http.services.rainloop.loadbalancer.server.port=8888"
            - "traefik.http.routers.rainloop.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.rainloop.entrypoints=websecure"
            - "traefik.http.routers.rainloop.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private