version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpnwireguard
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=${USERNAME}     # Required
      - PASS=${PASSWORD}         # Required
      - CONNECT=${CONNECT}
      - TECHNOLOGY=NordLynx
      - NETWORK=${NETWORK}  # So it can be accessed within the local network
    ports:
      - 8080:8080
      - 8686:8686
      - 9117:9117
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    security_opt:
      - no-new-privileges:true

  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - ../vpn/data/qbittorrent/config:/config
      - ../vpn/data/media/qbittorrent:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ../vpn/data/lidarr/config:/config
      - ../vpn/data/media:/media
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true
      
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ../vpn/data/jackett/config:/config
      - ../vpn/data/jackett/downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true
