version: "3"

services:
  samba: 
    container_name: samba
    command: "-s \"torrents;/media/torrents;yes;no;no\""
    environment: 
      - "NMBD=True"
      - "RECYCLE=False"
      - "USER=simon.haas;MeinBrutalesPasswort"
      - "PERMISSIONS"
    hostname: samba
    image: dperson/samba
    network_mode: host
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes: 
      - "../samba/data/torrents:/media/torrents"