version: "3.6"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      WEBUI_PORT: 8080 # admin/adminadmin
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/qbittorrent/downloads:/downloads
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: container:gluetun # see ../gluetun/docker-compose.yml
