version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID:
      PGID:
      TZ:
      SERVERURL:
      SERVERPORT:
      PEERS:
      PEERDNS:
      INTERNAL_SUBNET:
      ALLOWEDIPS:
      LOG_CONFS:
    volumes:
      - ./data/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped
