version: '3.7'
services:
  cryptofolio:
    image: xtrendence/cryptofolio:latest
    ports:
      - "8084:80"
    volumes:
      - ./data:/var/www/html/api/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.cryptofolio.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.cryptofolio.entrypoints: websecure
      traefik.http.services.cryptofolio.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1