version: '3.7'
services:
  cryptofolio:
    image: xtrendence/cryptofolio:latest
    volumes:
      - ./data:/var/www/html/api/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.cryptofolio.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.cryptofolio.entrypoints: websecure
      traefik.http.services.cryptofolio.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: cryptofolio
      homepage.icon: cryptofolio
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Crypto Currency Tracker

networks:
  traefik:
    name: zone1