---
version: "2.1"
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest
    environment:
      PUID:
      PGID:
      TZ:
    volumes:
      - ./data:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.xbackbone.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.xbackbone.entrypoints: websecure
      traefik.http.services.xbackbone.loadbalancer.server.port: 80
      homepage.group: ${HOMEPAGE_GROUP}
      homepage.name: ${HOMEPAGE_NAME}
      homepage.icon: ${HOMEPAGE_ICON}
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: ${HOMEPAGE_DESCRIPTION}

networks:
  default:
    name: zone1
    external: true
