version: "3.6"
services:
    privoxy:
        image: vimagick/privoxy
        ports:
          - "8118:8118"
        volumes:
          - ./data/user.action:/etc/privoxy/user.action
          - ./data/user.filter:/etc/privoxy/user.filter
        cap_add:
          - NET_ADMIN
        restart: always