version: "3.6"
services:
  grist:
    image: gristlabs/grist
    volumes:
      - ./data:/persist
    environment:
      APP_HOME_URL: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.grist.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.grist.entrypoints: websecure
      traefik.http.services.grist.loadbalancer.server.port: 8484

networks:
  traefik:
    name: zone1
    external: true
