version: "3.6"
services:
    traefik:
      hostname: traefik
      image: traefik:v1.7.16
      container_name: traefik
      restart: always
      domainname: simon-haas.eu
      networks:
        - default
        - traefik_proxy
      ports:
        - "80:80"
        - "443:443"
        - "8081:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.simon-haas.eu"  
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=simon-haas.eu"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
        # - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/traefik.toml:/etc/traefik/traefik.toml
        - ./traefik/servers.toml:/servers.toml
        - ./shared:/shared
        - ./fullchain.pem:/cert.pem
        - ./privkey.pem:/privkey.pem

    redis:
      image: redis:alpine
      restart: always
      container_name: redis
      networks:
        - traefik_proxy
      volumes:
        - ./redis:/data

    portainer:
      image: portainer/portainer
      container_name: portainer
      restart: always
      networks:
        - traefik_proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer:/data
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=9000"
          
    mariadb:
       image: mariadb
       container_name: "mariadb"
       hostname: mariadb
       networks:
        - traefik_proxy
       volumes:
           - ./mariadb:/var/lib/mysql
       ports:
         - target: 3306
           published: 3306
           protocol: tcp
           mode: host
       restart: always
       environment:
         - MYSQL_ROOT_PASSWORD=keinerweisdas
         - MYSQL_PASSWORD=mysql
         - MYSQL_DATABASE=nextcloud
         - MYSQL_USER=nextcloud

    openvpn:
      cap_add:
        - NET_ADMIN
      image: kylemanna/openvpn
      container_name: openvpn
      ports:
        - "1194:1194/udp"
      restart: always
      volumes:
        - ./openvpn-data/conf:/etc/openvpn

    adminer:
      container_name: adminer
      image: adminer
      restart: always
      networks:
        - traefik_proxy
      labels:
        - "traefik.backend=adminer"
        - "traefik.frontend.rule=Host:adminer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
