version: "3.6"
services:
    ddclient:
      image: linuxserver/ddclient
      container_name: ddclient
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Europe/London
      volumes:
        - ./ddclient/config:/config
      restart: unless-stopped

    traefik:
      hostname: traefik
      image: traefik:v1.7.16
      container_name: traefik
      restart: always
      domainname: simon-haas.eu
      networks:
        - default
        - traefik_proxy
      ports:
        - "80:80"
        - "443:443"
        - "8081:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.simon-haas.eu"  
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=simon-haas.eu"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
        # - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/traefik.toml:/etc/traefik/traefik.toml
        - ./traefik/servers.toml:/servers.toml
        - ./shared:/shared
        - ./fullchain.pem:/cert.pem
        - ./privkey.pem:/privkey.pem

    # portainer:
    #   image: portainer/portainer
    #   container_name: portainer
    #   restart: always
    #   volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ./portainer:/data
    #     - ./shared:/shared
    #   labels:
    #     - "traefik.backend=portainer"
    #     - "traefik.docker.network=web"
    #     - "traefik.frontend.rule=Host:portainer.simon-haas.eu"
    #     - "traefik.enable=true"
    #     - "traefik.port=9000"

    minetest:
      image: linuxserver/minetest
      container_name: minetest
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - CLI_ARGS="--server --worldname MyWorld --gameid minetest" #optional
      volumes:
        - ./minetest:/config/.minetest
      ports:
        - 30000:30000/udp
      restart: unless-stopped

    librespeed:
      image: adolfintel/speedtest
      restart: always
      environment: 
          - MODE=standalone
      labels:
        - "traefik.backend=speedtest"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:speedtest.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"

    etiketten:
      container_name: etiketten_nginx
      image: nginx
      restart: always
      volumes:
        - ./etiketten:/usr/share/nginx/html
      labels:
        - "traefik.backend=etiketten"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:etiketten.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"

    rainloop:
      container_name: "rainloop"
      image: solidnerd/rainloop:1.10.5.192
      volumes:
        - ./rainloop:/var/www/rainloop/data
      labels:
        - "traefik.backend=rainloop"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:rainloop.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"

    redis:
      image: redis:alpine
      restart: always
      volumes:
        - ./redis:/data

    nextcloud:
      container_name: nextcloud
      restart: always
      image: nextcloud:18
      links:
        - mariadb
        - redis
      environment:
        - REDIS_HOST=redis
      volumes:
        - ./nextcloud:/var/www/html
      labels:
        - "traefik.backend=nextcloud"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:nextcloud.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"

    calibre-web:
      image: linuxserver/calibre-web
      container_name: calibre-web
      volumes:
        - ./calibre-web/config:/config
        - ./calibre-web/books:/books
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      labels:
        - "traefik.backend=calibre-web"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:calibre-web.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8083"

    gogs:
        container_name: gogs
        restart: always
        image: gogs/gogs
        # links:
        #     - mariadb
        ports:
        # to keep backwards compatibility with ip:port
          - "3000:3000"
          - "10022:22"
        environment:
          - PUID=1000
          - PGID=1000
        volumes:
          - ./gogs:/data
        labels:
          - "traefik.backend=gogs"
          - "traefik.docker.network=web"
          - "traefik.frontend.rule=Host:gogs.simon-haas.eu"
          - "traefik.enable=true"
          - "traefik.port=3000"
          
    mariadb:
       image: mariadb
       container_name: "mariadb"
       hostname: mariadb
       volumes:
           - ./mariadb:/var/lib/mysql
       ports:
         - target: 3306
           published: 3306
           protocol: tcp
           mode: host
       restart: always
       environment:
         - MYSQL_ROOT_PASSWORD=keinerweisdas
         - MYSQL_PASSWORD=mysql
         - MYSQL_DATABASE=nextcloud
         - MYSQL_USER=nextcloud

    # openvpn:
    #   cap_add:
    #   - NET_ADMIN
    #   build: ./images/docker-openvpn
    #   container_name: openvpn
    #   ports:
    #   - "1194:1194/udp"
    #   restart: always
    #   volumes:
    #   - ./docker-vpn/openvpn-data/conf:/etc/openvpn

    openvpn:
      cap_add:
        - NET_ADMIN
      image: kylemanna/openvpn
      container_name: openvpn
      ports:
        - "1194:1194/udp"
      restart: always
      volumes:
        - ./openvpn-data/conf:/etc/openvpn

    airsonic:
      image: linuxserver/airsonic
      container_name: airsonic
      environment:
        - JAVA_OPTS=-Dserver.use-forward-headers=true
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
#        - CONTEXT_PATH=<URL_BASE> #optional
#        - JAVA_OPTS=<options> #optional
      volumes:
        - ./airsonic/config:/config
        - ./airsonic/music:/music
        - ./airsonic/playlists:/playlists
        - ./airsonic/podcasts:/podcasts
        - ./airsonic/media:/media #optional
        - ./airsonic/audiobooks:/audiobooks
#      ports:
#        - 4040:4040
      restart: unless-stopped
      labels:
        - "traefik.backend=airsonic"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:airsonic.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=4040"

#    airsonic-music:
#      image: linuxserver/airsonic
#      container_name: airsonic-music
#      environment:
#        - JAVA_OPTS=-Dserver.use-forward-headers=true
#        - PUID=1000
#        - PGID=1000
#        - TZ=Europe/London
#      volumes:
#        - ./airsonic-music/config:/config
#        - ./airsonic-music/music:/music
#        - ./airsonic-music/playlists:/playlists
#        - ./airsonic-music/podcasts:/podcasts
#        - ./airsonic-music/media:/media
#        - ./airsonic-music/audiobooks:/audiobooks
#      restart: unless-stopped
#      labels:
#        - "traefik.backend=airsonic-music"
#        - "traefik.docker.network=web"
#        - "traefik.frontend.rule=Host:airsonic-music.simon-haas.eu"
#        - "traefik.enable=true"
#        - "traefik.port=4040"

    clarkson:
      image: linuxserver/clarkson
      container_name: clarkson
      environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_HOST=mariadb
        - MYSQL_USERNAME=clarkson_user
        - MYSQL_PASSWORD=supersecretpassword
        - ENABLE_REGISTRATIONS=true
        - TZ=Europe/London
      restart: unless-stopped
      labels:
        - "traefik.backend=clarkson"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:clarkson.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=3000"

    fireflyiii:
      image: jc5x/firefly-iii:latest
      volumes:
        # - firefly_iii_export:/var/www/firefly-iii/storage/export
        # - firefly_iii_upload:/var/www/firefly-iii/storage/upload
        - ./firefly-iii:/var/www/firefly-iii/storage
      env_file: ./firefly-iii/.env
      # ports:
      #   - 80:8080
      links:
        - mariadb
      user: 1000:1000
      labels:
        - "traefik.backend=firefly"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:firefly.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

    # fireflyiiidb:
    #   image: yobasystems/alpine-mariadb:latest
    #   environment:
    #     - MYSQL_RANDOM_ROOT_PASSWORD=yes
    #     - MYSQL_USER=firefly
    #     - MYSQL_PASSWORD=secret_firefly_password
    #     - MYSQL_DATABASE=firefly
    #   volumes:
    #     - firefly_iii_db:/var/lib/mysql

    adminer:
      image: adminer
      restart: always
      labels:
        - "traefik.backend=adminer"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:adminer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
