version: "3.6"
services:
    traefik:
      hostname: traefik
      image: traefik:v1.7.16
      container_name: traefik
      restart: always
      domainname: simon-haas.eu
      networks:
        - default
        - traefik_proxy
      ports:
        - "80:80"
        - "443:443"
      environment:
        - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.simon-haas.eu"  
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=simon-haas.eu"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/traefik.toml:/etc/traefik/traefik.toml
        - ./traefik/servers.toml:/servers.toml
        - ./traefik/acme.json:/acme.json # touch traefik/acme.json && chmod 600 traefik/acme.json

    # portainer:
    #   image: portainer/portainer
    #   container_name: portainer
    #   restart: always
    #   networks:
    #     - traefik_proxy
    #   volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ./portainer:/data
    #   labels:
    #     - "traefik.backend=portainer"
    #     - "traefik.frontend.rule=Host:portainer.simon-haas.eu"
    #     - "traefik.enable=true"
    #     - "traefik.port=9000"

    dyndns:
      image: tunix/digitalocean-dyndns
      container_name: dyndns
      restart: always
      environment:
        - DIGITALOCEAN_TOKEN=${DO_AUTH_TOKEN}
        - DOMAIN=${DOMAIN}
        - NAME=${DYNDNS_NAME}

    # openvpn:
    #   cap_add:
    #     - NET_ADMIN
    #   image: kylemanna/openvpn
    #   container_name: openvpn
    #   ports:
    #     - "1194:1194/udp"
    #   restart: always
    #   volumes:
    #     - ./openvpn-data/conf:/etc/openvpn

    adminer:
      container_name: adminer
      image: adminer
      restart: always
      networks:
        - traefik_proxy
      labels:
        - "traefik.backend=adminer"
        - "traefik.frontend.rule=Host:adminer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

    wireguard:
      image: ghcr.io/linuxserver/wireguard
      container_name: wireguard
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=${TZ}
        - SERVERURL=${SERVERURL} #optional
        - SERVERPORT=51820 #optional
        - PEERS=${PEERS} #optional
        #- PEERDNS=auto #optional
        #- INTERNAL_SUBNET=10.13.13.0 #optional
        #- ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
      volumes:
        - ./wireguard/data/config:/config
        - /lib/modules:/lib/modules
      ports:
        - 51820:51820/udp
      #sysctls:
      #  - net.ipv4.conf.all.src_valid_mark=1
      restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
