version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8009:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../paperless-ng/data/data:/usr/src/paperless/data
      - ../paperless-ng/data/media:/usr/src/paperless/media
      - ../paperless-ng/data/export:/usr/src/paperless/export
      - ../paperless-ng/data/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    networks:
        - traefik_proxy
    labels:
        - "traefik.backend=paperless"
        - "traefik.frontend.rule=Host:paperless.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8000"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge