version: '3'
services:
  wol:
    image: "dabondi/go-rest-wol"
    ports:
      - "8081:8080"
    volumes:
      - ./config.csv:/app/computer.csv
    container_name: wol
    restart: always
    networks: 
        - traefik
    security_opt:
        - no-new-privileges:true
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.wol.loadbalancer.server.port=8080"
        - "traefik.http.routers.wol.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.wol.entrypoints=websecure"
        - "traefik.http.routers.wol.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik