version: "3.6"
services:
  wol:
    image: "dabondi/go-rest-wol"
    volumes:
      - ./config.csv:/app/computer.csv
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.wol.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.wol.entrypoints: websecure
      traefik.http.services.wol.loadbalancer.server.port: 8080
      homepage.group: Infrastructure
      homepage.name: WakeOnLan
      homepage.icon: wol
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: wol-service
      
networks:
  traefik:
    name: zone1
    external: true
