version: '3.7'

services:
  bloben:
    image: 'bloben/app:latest'
    volumes:
      - ./data/logs:/logs
    env_file:
      - .env
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.bloben.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.bloben.entrypoints: websecure
      traefik.http.services.bloben.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: bloben
      homepage.icon: bloben
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: calendar UI

  databaseBloben14:
    image: 'postgres:14.5-bullseye'
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik

  redisBloben:
    image: redis:7.0.5-bullseye
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: zone1
    external: true
