version: "3.6"
services:
    drone:
      image: drone/drone:1
      container_name: drone
      restart: always
      volumes: 
        - ./data:/data
      environment: 
        - DRONE_AGENTS_ENABLED=true
        - DRONE_GOGS_SERVER=https://gogs.simon-haas.eu
        - DRONE_RPC_SECRET=thisissecret
        - DRONE_SERVER_HOST=drone.simon-haas.eu
        - DRONE_SERVER_PROTO=https
      networks:
          - traefik_proxy
      labels:
          - "traefik.backend=drone"
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:drone.simon-haas.eu"
          #- "traefik.docker.network=web"
          #- "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.port=80"

    drone-runner:
      image: drone/drone-runner-docker:1
      container_name: runner
      restart: always
      ports:
        - "3000:3000"
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      environment: 
        - DRONE_RPC_PROTO=https
        - DRONE_RPC_HOST=drone.simon-haas.eu
        - DRONE_RPC_SECRET=thisissecret
        - DRONE_RUNNER_CAPACITY=2
        - DRONE_RUNNER_NAME=drone-runner

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge