version: '3.3'

services:
  tubearchivist:
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8089:8000
    volumes:
      - ./data/media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=${SUB_DOMAIN}.${SERVER_DOMAIN}         # set your host name
      - TA_USERNAME=${TA_USERNAME}           # your initial TA credentials
      - TA_PASSWORD=${TA_PASSWORD}              # your initial TA credentials
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}         # set password for Elasticsearch
      - TZ=${TZ}                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.tubearchivist.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.tubearchivist.entrypoints: websecure
      traefik.http.services.tubearchivist.loadbalancer.server.port: 8000


  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
    networks:
      - traefik

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.3.2
    restart: unless-stopped
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"       # matching Elasticsearch password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    networks:
      - traefik

volumes:
  #media:
  cache:
  redis:
  es:

networks:
  traefik:
    name: zone1