version: "3.6"
services:
  adminer:
    image: adminer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.adminer.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.adminer.entrypoints: websecure
      traefik.http.services.adminer.loadbalancer.server.port: 8080

networks:
  traefik:
    name: zone1
    external: true
