version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    volumes:
      - ./data/audiobooks:/audiobooks
      - ./data/metadata:/metadata
      - ./data/config:/config
    restart: unless-stopped
    container_name: audiobookshelf
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.audiobookshelf.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1