version: "3.6"
services:
  yacht:
    image: selfhostedpro/yacht
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.yacht.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`) # admin@yacht.local / pass
      traefik.http.routers.yacht.entrypoints: websecure
      traefik.http.services.yacht.loadbalancer.server.port: 8000

networks:
  traefik:
    name: zone1
    external: true
