version: "3.7"

services:
  proxy:
    image: hoppscotch/proxyscotch
    container_name: hoppscotch_proxy
    #ports:
    #  - 9159:9159
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=hoppscotch-proxy"
      - "traefik.frontend.rule=Host:hoppscotch-proxy.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=9159"
  web:
    image: registry.simon-haas.eu/hoppscotch-web
    restart: always
    # volumes:
    #   - "./.hoppscotch:/app/.hoppscotch"
    #   - "./assets:/app/assets"
    #   - "./directives:/app/directives"
    #   - "./layouts:/app/layouts"
    #   - "./middleware:/app/middleware"
    #   - "./pages:/app/pages"
    #   - "./plugins:/app/plugins"
    #   - "./static:/app/static"
    #   - "./store:/app/store"
    #   - "./components:/app/components"
    #   - "./helpers:/app/helpers"
    #ports:
    #  - "3000:3000"
    # environment:
    #   HOST: 0.0.0.0
    container_name: hoppscotch_web
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=hoppscotch"
      - "traefik.frontend.rule=Host:hoppscotch.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=3000"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge