version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    container_name: transmission
    restart: always
    networks: 
        - traefik
    security_opt:
        - no-new-privileges:true
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"
        - "traefik.http.routers.transmission.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik