version: "2"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ:
      USER:
      PASS:
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
    restart: always
    network_mode: container:gluetun # see ../gluetun/docker-compose.yml
    labels:
      homepage.group: Arr
      homepage.name: Transmission
      homepage.icon: transmission
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Torrent downloader
      homepage.widget.type: transmission
      homepage.widget.url: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.widget.username: ${USER}
      homepage.widget.password: ${PASS}
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
      