# username: admin
# password: (blank)

version: "3.6"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    volumes:
      - ./data/var_lib_motioneye:/var/lib/motioneye
    container_name: motioneye
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.motioneye.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.motioneye.entrypoints: websecure
      traefik.http.services.motioneye.loadbalancer.server.port: 8765

networks:
  traefik:
    name: zone1
