---
version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data:/config
    restart: unless-stopped