version: "3.6"
services:
  guacamole:
    image: oznu/guacamole
    volumes:
      - ./data/config:/config
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.guacamole.rule: Host(`guacamole.${SERVER_DOMAIN}`)
      traefik.http.routers.guacamole.entrypoints: websecure
      traefik.http.services.guacamole.loadbalancer.server.port: 8080 # guacadmin/guacadmin
      homepage.group: Infrastructure
      homepage.name: Guacamole
      homepage.icon: guacamole
      homepage.href: https://guacamole.${SERVER_DOMAIN}
      homepage.description: Remote Desktop Client

networks:
  traefik:
    name: zone1
