version: "2"
services:
  guacamole:
    image: oznu/guacamole
    volumes:
      - ./data/config:/config
    container_name: guacamole
    restart: always
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
        - traefik.zone=private
        - "traefik.enable=true"
        - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
        - "traefik.http.routers.guacamole.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.guacamole.entrypoints=websecure"
        - "traefik.http.routers.guacamole.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private