version: "3.6"
services:
  guacamole:
    image: oznu/guacamole
    volumes:
      - ./data/config:/config
    container_name: guacamole
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.guacamole.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.guacamole.entrypoints: websecure
      traefik.http.services.guacamole.loadbalancer.server.port: 8080 # guacadmin/guacadmin

networks:
  traefik:
    name: zone1
