version: "3.6"
services:
    etiketten:
        container_name: etiketten_nginx
        image: registry.simon-haas.eu/etiketten
        restart: always
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=etiketten"
            - "traefik.frontend.rule=Host:etiketten.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge