version: '3.8'

services:
  fittrackee-db:
    build:
      context: ./docker-fittrackee/db
      dockerfile: Dockerfile
    volumes:
    - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./docker-fittrackee/.env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      com.centurylinklabs.watchtower.enable: false


  fittrackee:
    build:
      context: ./docker-fittrackee
      dockerfile: Dockerfile
    env_file:
      - ./docker-fittrackee/.env
    depends_on:
      - fittrackee-db
    links:
      - fittrackee-db
    volumes:
      - ./data/uploads:/uploads:rw
      - ./data/logs:/logs:rw
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.fittrackee.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.fittrackee.entrypoints: websecure
      traefik.http.services.fittrackee.loadbalancer.server.port: 5000
      homepage.group: Media
      homepage.name: fittrackee
      homepage.icon: fittrackee
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: outdoor fitness tracker
      com.centurylinklabs.watchtower.enable: false

  redis:
    image: "redis:latest"
    hostname: redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

networks:
  traefik:
    name: zone1
    external: true
