version: "2.1"
services:
  uptimekuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    container_name: uptimekuma
    networks:
        - traefik_proxy
    security_opt:
        - no-new-privileges:true
    labels:
        - "traefik.backend=uptimekuma"
        - "traefik.frontend.rule=Host:uptimekuma.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=9091"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge