version: "3.6"
services:
    proxmox:
        image: nginx
        container_name: proxmox
        restart: always
        security_opt:
            - no-new-privileges:true
        networks:
            - traefik
        labels:
            my.zone: zone1
            traefik.enable: true
            traefik.http.routers.proxmox.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
            traefik.http.routers.proxmox.entrypoints: websecure
            traefik.http.services.proxmox.loadbalancer.server.port: 443
        volumes:
            - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
        environment:
            - NGINX_PROXMOX_IP=${IP}

networks:
    traefik:
        name: zone1