version: "3"
services:
  vpn:
  # TEST: docker exec -it vpn curl ifconfig.me
    image: ghcr.io/bubuntux/nordlynx
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NET_LOCAL=${NET_LOCAL}
      - QUERY=filters\[country_id\]=${COUNTRY_ID}&filters\[servers_groups\]\[identifier\]=${SERVER_TYPE}
# TODO reverse proxy with url
    ports:
      - 8080:8080 # qbittorrent admin/adminadmin
      - 9117:9117 # jackett
      - 8191:8191 # flaresolverr
      - 8686:8686 # lidarr, music
      - 7878:7878 # radarr, movies
      - 8989:8989 # sonarr, series
    security_opt:
      - no-new-privileges:true

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent-vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080 # admin/adminadmin
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/qbittorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/lidarr/config:/config
      - ./data/media:/media
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/radarr/config:/config
      - ./data/radarr/media:/media
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/sonarr/config:/config
      - ./data/sonarr/media:/media
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true
      
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ./data/jackett/config:/config
      - ./data/jackett/downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    security_opt:
      - no-new-privileges:true
# curl -L -X POST 'http://192.168.155.212:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd": "request.get","url":"http://www.google.com/","maxTimeout": 60000}'
