version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - ./config:/config
    #ports:
    #  - 8080:8080
    networks:
        - traefik_proxy
    labels:
        - "traefik.backend=guacamole"
        - "traefik.frontend.rule=Host:guacamole.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
traefik_proxy:
    external:
        name: traefik_proxy
default:
    driver: bridge