version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
      - APP_URL=https://bookstack.simon-haas.eu
    volumes:
      - ./app/data:/config
    #ports:
    #  - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
    - traefik_proxy
    labels:
      - "traefik.backend=bookstack"
      - "traefik.frontend.rule=Host:bookstack.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - ./db/data:/config
    networks:
      - traefik_proxy
    restart: unless-stopped

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge
