# docker run \
#   -d \
#   --name baserow \
#   -e BASEROW_PUBLIC_URL=https://www.yourdomain.com \
#   -v baserow_data:/baserow/data \
#   -p 80:80 \
#   --restart unless-stopped \
#   baserow/baserow:1.10.1

version: "3.6"
services:
  baserow:
    image: baserow/baserow
    environment:
      - BASEROW_PUBLIC_URL=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
    volumes:
      - ./data:/baserow/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.baserow.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.baserow.entrypoints: websecure
      traefik.http.services.baserow.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1
