version: "3.4"

services:
  own-my-money:
    image: nioc/own-my-money:latest
    environment:
      TZ: ${TZ}
      OMM_BASE_URI: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      OMM_DB_HOST: db
      OMM_DB_USER: ${MARIADB_USER}
      OMM_DB_PWD: ${MARIADB_PASSWORD}
      OMM_DB_NAME: ${MARIADB_DATABASE}
      # Uncomment after completing setup
      # OMM_SETUP: 1
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.own-my-money.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.own-my-money.entrypoints: websecure
      traefik.http.services.own-my-money.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: Own my Money
      homepage.icon: own-my-money
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: personal finance tool

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

networks:
  traefik:
    name: zone1