version: "3"
services:
  watchyourlan:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - ./data:/data
    environment:
      TZ:
      IFACE:
      DBPATH: "/data/db.sqlite"
      GUIIP: "0.0.0.0"
      GUIPORT: "8840"
      TIMEOUT: "120"
      SHOUTRRR_URL: ""
      THEME: "darkly"
    security_opt:
      - no-new-privileges:true
# I use nginx-proxy-manager for this service, not traefik. You can find nginx-proxy-manager also in this repository.
