version: "3"
services:
  metube:
    image: alexta69/metube
    restart: unless-stopped
    volumes:
      - ./data/downloads:/downloads
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.metube.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.metube.entrypoints: websecure
      traefik.http.services.metube.loadbalancer.server.port: 8081
      traefik.http.routers.metube.middlewares: authelia@docker
      homepage.group: Media
      homepage.name: Metube
      homepage.icon: metube
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Youtube Downloader

networks:
  traefik:
    name: zone1
    external: true
