version: "3.3"
services:
  speedtest:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - ./data:/config
    environment:
      - TZ=
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.speedtest-tracker.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.speedtest-tracker.entrypoints: websecure
      homepage.group: Infrastructure
      homepage.name: Speedtest-tracker
      homepage.icon: speedtest-tracker
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Speedtest-tracker
      homepage.widget.type: speedtest
      homepage.widget.url: https://${SUB_DOMAIN}.${SERVER_DOMAIN}/

networks:
  traefik:
    name: zone1