version: "3.6"
services:
    keeweb:
        image: antelle/keeweb
        container_name: keeweb
        restart: always
        networks:
        - traefik_proxy
        labels:
        - "traefik.backend=keeweb"
        - "traefik.frontend.rule=Host:keeweb.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge