# https://github.com/pi-hole/docker-pi-hole/#installing-on-ubuntu
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      #- "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'dasistganzgeheim'
    volumes:
      - '../pihole/data/etc-pihole/:/etc/pihole/'
      - '../pihole/data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=pihole2"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:pihole2.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge