version: "3.6"
services:
    etiketten:
        container_name: cyberchef
        image: registry.simon-haas.eu/cyberchef
        restart: always
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=cyberchef"
            - "traefik.frontend.rule=Host:cyberchef.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge