version: "3.6"
services:
    airsonic:
        image: linuxserver/airsonic
        container_name: airsonic
        networks:
            - traefik_proxy
        environment:
            - JAVA_OPTS=-Dserver.use-forward-headers=true
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./data/config:/config
            - ./data/music:/music
            - ./data/playlists:/playlists
            - ./data/podcasts:/podcasts
            - ./data/media:/media #optional
        restart: unless-stopped
        labels:
            - "traefik.backend=airsonic-music"
            - "traefik.frontend.rule=Host:airsonic-music.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=4040"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge