# docker container run -dit -p 8080:5000 -p 8000:8000 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:2.1.0-latest

version: '3.7'

services:
  checkmk:
    image: checkmk/check-mk-raw:2.1.0-latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/omd/sites
    ports:
      - 8000:8000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.checkmk.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.checkmk.entrypoints: websecure
      traefik.http.services.checkmk.loadbalancer.server.port: 5000
      homepage.group: Infrastructure
      homepage.name: checkmk
      homepage.icon: checkmk
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Infrastructure Monitoring
      
networks:
  traefik:
    name: zone1