version: '3.5'

services:
    traefik:
        restart: always
        image: "traefik:2.6"
        container_name: traefik_public
        command:
            - "--log.level=DEBUG"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls.certResolver=myresolver"
            - "--certificatesresolvers.myresolver.acme.storage=acme.json"
            - "--certificatesResolvers.myresolver.acme.email=me@simonhaas.eu" # Let's Encrypt staging server
            # - "--certificatesResolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            - "--certificatesResolvers.myresolver.acme.dnsChallenge=true"
            - "--certificatesResolvers.myresolver.acme.dnschallenge.provider=digitalocean"
            - "--certificatesResolvers.myresolver.acme.dnschallenge.resolvers=8.8.4.4:53,8.8.8.8:53"
            - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=0"
            - --providers.docker.constraints=Label(`traefik.zone`, `public`)
        ports:
# use these commands on a different machine locally to forward requests from your local network to these ports, use pihole or something similar to change the A-records when resolving locally
# https://github.com/troglobit/redir
# redir -I http :80 192.168.155.212:880
# redir -I https :443 192.168.155.212:8443
            - "880:80"
            - "8443:443"
            - "8088:8080"
        networks:
            - traefik_public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./acme.json:/acme.json
        env_file:
            - .env
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_public"
            - "traefik.http.routers.traefik.entrypoints=web"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.tls.certresolver=myresolver"
            - "traefik.http.routers.traefik.tls.domains[0].main=simonhaas.eu"
            - "traefik.http.routers.traefik.tls.domains[0].sans=*.simonhaas.eu"

            - --api.dashboard=false
            # - --api.insecure=true
            # - traefik.zone=public
            # - "traefik.http.routers.traefik.rule=Host(`traefik.simonhaas.eu`)"
            # - "traefik.http.routers.api.tls=true"
            # - "traefik.http.routers.api.entrypoints=websecure"
            # - "traefik.http.routers.api.rule=Host(`traefik.simonhaas.eu`)"
            # - "traefik.http.routers.api.service=api@internal"
            # - "traefik.http.routers.api.middlewares=api-auth"
            # - "traefik.http.middlewares.api-auth.basicauth.users=admin:$$apr1$$DNuSHMb0$$ZTvM595flViQSR2ZUJTzu0"

            # Use Middlewares for a global redirect to https
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
            - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.redirs.entrypoints=web"
            - "traefik.http.routers.redirs.middlewares=redirect-to-https"

    gitlab:
        restart: always
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        hostname: gitlab.simonhaas.eu
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://gitlab.simonhaas.eu'
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                nginx['http2_enabled'] = false
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
                nginx['proxy_set_headers'] = {
                    "Host" => "$$http_host",
                    "X-Real-IP" => "$$remote_addr",
                    "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
                    "X-Forwarded-Proto" => "https",
                    "X-Forwarded-Ssl" => "on"
                }
        ports:
            - "2222:22"
        labels:
            - traefik.zone=public
            - "traefik.enable=true"
            - "traefik.gitlab.frontend.rule=Host:gitlab.simonhaas.eu"
            - "traefik.gitlab.port=80"

            - "traefik.frontend.entryPoints=websecure"
            - "traefik.port=80"

            #  Host settings for GitLab itself
            - traefik.http.middlewares.gitlab-https-redirect.redirectscheme.scheme=https
            - traefik.http.routers.gitlab.middlewares=gitlab-https-redirect
            - traefik.http.services.gitlab.loadbalancer.server.port=80

            - traefik.http.routers.gitlab.tls=true
            - traefik.http.routers.gitlab.rule=Host(`gitlab.simonhaas.eu`)
            - traefik.http.routers.gitlab.tls.certresolver=myresolver
            - traefik.http.routers.gitlab.entrypoints=websecure
            - traefik.docker.network=traefik_public
        expose:
            - "80"
            - "443"
            - "5200"
        volumes:
            - ./config:/etc/gitlab/
            - ./logs:/var/log/gitlab/
            - ./data:/var/opt/gitlab/
            - /etc/localtime:/etc/localtime:ro
        networks:
            - traefik_public

networks:
    traefik_public:
        external:
            name: traefik_public
