global: {}
entryPoints:
  http:
    address: :80
  https:
    address: :443
  traefik:
    address: :9000
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    swarmModeRefreshSeconds: 15s
api:
  insecure: true
  dashboard: true
log:
  level: ERROR
certificatesResolvers:
  default:
    acme:
      email: me@simonhaas.eu
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: acme.json
      dnsChallenge:
        provider: digitalocean
