loglevel = "DEBUG"

[backends]
    [backends.tvheadend]
        [backends.tvheadend.servers.tvheadend]
            url = "http://192.168.155.204:9981"
    [backends.code-server]
        [backends.code-server.servers.code-server]
            url = "http://192.168.155.215:8080"
    [backends.pihole]
        [backends.pihole.servers.pihole]
            url = "http://192.168.155.2"

[frontends]
    [frontends.tvheadend]
        backend = "tvheadend"
    [frontends.tvheadend.routes.tvheadend]
        rule = "Host:tvheadend.simon-haas.eu"
    [frontends.code-server]
        backend = "code-server"
    [frontends.code-server.routes.code-server]
        rule = "Host:code-server.simon-haas.eu"
    [frontends.pihole]
        backend = "pihole"
    [frontends.pihole.routes.pihole]
        rule = "Host:pihole.simon-haas.eu"
