loglevel = "DEBUG"

[backends]
    [backends.tvheadend]
        [backends.tvheadend.servers.tvheadend]
            url = "http://192.168.153.204:9981"
    [backends.motioneyeos]
        [backends.motioneyeos.servers.motioneyeos]
            url = "http://192.168.153.211:80"
    [backends.code-server]
        [backends.code-server.servers.code-server]
            url = "http://192.168.153.215:8080"
    [backends.jupyter]
        [backends.jupyter.servers.jupyter]
            url = "http://192.168.153.221:8888"

[frontends]
    [frontends.tvheadend]
        backend = "tvheadend"
    [frontends.tvheadend.routes.tvheadend]
        rule = "Host:tvheadend.simon-haas.eu"
    [frontends.motioneyeos]
        backend = "motioneyeos"
    [frontends.motioneyeos.routes.motioneyeos]
        rule = "Host:motioneyeos.simon-haas.eu"
    [frontends.code-server]
        backend = "code-server"
    [frontends.code-server.routes.code-server]
        rule = "Host:code-server.simon-haas.eu"
    [frontends.jupyter]
        backend = "jupyter"
    [frontends.jupyter.routes.jupyter]
        rule = "Host:jupyter.simon-haas.eu"