loglevel = "DEBUG"

[backends]
    [backends.tvheadend]
        [backends.tvheadend.servers.tvheadend]
            url = "http://192.168.153.204:9981"
    [backends.motioneyeos]
        [backends.motioneyeos.servers.motioneyeos]
            url = "http://192.168.153.211:80"

[frontends]
    [frontends.tvheadend]
        backend = "tvheadend"
    [frontends.tvheadend.routes.tvheadend]
        rule = "Host:tvheadend.simon-haas.eu"
    [frontends.motioneyeos]
        backend = "motioneyeos"
    [frontends.motioneyeos.routes.motioneyeos]
        rule = "Host:motioneyeos.simon-haas.eu"
