loglevel = "DEBUG"

[backends]
    [backends.tvheadend]
        [backends.tvheadend.servers.tvheadend]
            url = "http://192.168.153.204:9981"
    [backends.motioneyeos]
        [backends.motioneyeos.servers.motioneyeos]
            url = "http://192.168.153.211:80"
    [backends.code-server]
        [backends.code-server.servers.code-server]
            url = "http://192.168.153.215:8080"
    [backends.pihole]
        [backends.pihole.servers.pihole]
            url = "http://192.168.153.2"
    [backends.wol-service]
        [backends.wol-service.servers.wol-service]
            url = "http://192.168.153.227"

[frontends]
    [frontends.tvheadend]
        backend = "tvheadend"
    [frontends.tvheadend.routes.tvheadend]
        rule = "Host:tvheadend.simon-haas.eu"
    [frontends.motioneyeos]
        backend = "motioneyeos"
    [frontends.motioneyeos.routes.motioneyeos]
        rule = "Host:motioneyeos.simon-haas.eu"
    [frontends.code-server]
        backend = "code-server"
    [frontends.code-server.routes.code-server]
        rule = "Host:code-server.simon-haas.eu"
    [frontends.pihole]
        backend = "pihole"
    [frontends.pihole.routes.pihole]
        rule = "Host:pihole.simon-haas.eu"
    [frontends.wol-service]
        backend = "wol-service"
    [frontends.wol-service.routes.wol-service]
        rule = "Host:wol.simon-haas.eu"