loglevel = "DEBUG"

[backends]
    [backends.tvheadend]
        [backends.tvheadend.servers.tvheadend]
            url = "http://192.168.155.204:9981"
    [backends.motioneyeos]
        [backends.motioneyeos.servers.motioneyeos]
            url = "http://192.168.155.211:80"
    [backends.code-server]
        [backends.code-server.servers.code-server]
            url = "http://192.168.155.215:8080"
    [backends.pihole]
        [backends.pihole.servers.pihole]
            url = "http://192.168.155.2"
    [backends.wol-service]
        [backends.wol-service.servers.wol-service]
            url = "http://192.168.155.227"
    [backends.umbrel]
        [backends.umbrel.servers.umbrel]
            url = "http://192.168.155.231"
    [backends.fittrackee]
        [backends.fittrackee.servers.fittrackee]
            url = "http://192.168.155.234:5000"

[frontends]
    [frontends.tvheadend]
        backend = "tvheadend"
    [frontends.tvheadend.routes.tvheadend]
        rule = "Host:tvheadend.simon-haas.eu"
    [frontends.motioneyeos]
        backend = "motioneyeos"
    [frontends.motioneyeos.routes.motioneyeos]
        rule = "Host:motioneyeos.simon-haas.eu"
    [frontends.code-server]
        backend = "code-server"
    [frontends.code-server.routes.code-server]
        rule = "Host:code-server.simon-haas.eu"
    [frontends.pihole]
        backend = "pihole"
    [frontends.pihole.routes.pihole]
        rule = "Host:pihole.simon-haas.eu"
    [frontends.wol-service]
        backend = "wol-service"
    [frontends.wol-service.routes.wol-service]
        rule = "Host:wol.simon-haas.eu"
    [frontends.umbrel]
        backend = "umbrel"
    [frontends.umbrel.routes.umbrel]
        rule = "Host:umbrel.simon-haas.eu"
    [frontends.fittrackee]
        backend = "fittrackee"
    [frontends.fittrackee.routes.fittrackee]
        rule = "Host:fittrackee.simon-haas.eu"
