#debug = true

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
#[api]
#  entryPoint = "traefik"
#  dashboard = true
#  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  #[entryPoints.http.auth.digest]
  #usersFile = ".htdigest"
    [entryPoints.https.tls]
   # [[entryPoints.https.tls.certificates]]
   # certFile = "/cert.pem"
   # keyFile = "/privkey.pem"

[file]
  watch = true
  filename = "servers.toml"

# Let's encrypt configuration
[acme]
 email = "me@simonhaas.eu" #any email id will work
 storage="acme.json"
 entryPoint = "https"
 acmeLogging=true
# onDemand = false #create certificate when container is created
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
   provider = "digitalocean"
#   delayBeforeCheck = 300
 [[acme.domains]]
    main = "*.simon-haas.eu"
# [[acme.domains]]
#    main = "*.EXAMPLE.COM"

# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "simon-haas.eu"
watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false