version: "3.6"
services:
  kasm:
    image: nginx
    container_name: kasm
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.kasm.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.kasm.entrypoints: websecure
      traefik.http.services.kasm.loadbalancer.server.port: 443
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro

networks:
  traefik:
    name: zone1
