version: "3.6"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../syncthing/data/appdata/config:/config
      - ../syncthing/data/data:/data
    ports:
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
    networks: 
        - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        - "traefik.http.routers.syncthing.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.syncthing.entrypoints=websecure"
        - "traefik.http.routers.syncthing.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik