version: "3.6"
services:
    nextcloud:
        container_name: nextcloud
        restart: always
        image: nextcloud:fpm-alpine
        depends_on: 
            - nextcloud-mariadb
            - nextcloud-redis
        networks:
            - traefik_proxy
        environment:
            - REDIS_HOST=nextcloud-redis
        volumes:
            - ./data:/var/www/html

    nextcloud-cron:
        image: nextcloud:fpm-alpine
        restart: always
        container_name: nextcloud-cron
        networks:
            - traefik_proxy
        volumes:
            - ./data:/var/www/html
        entrypoint: /cron.sh
        depends_on:
            - nextcloud-mariadb
            - nextcloud-redis

    nextcloud-web:
        build: ./web
        container_name: nextcloud-web
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./data:/var/www/html:ro
        depends_on:
            - nextcloud
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=nextcloud"
            - "traefik.frontend.rule=Host:nextcloud.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"
            - traefik.frontend.headers.STSSeconds=315360000

    nextcloud-mariadb:
        image: mariadb
        container_name: "nextcloud-mariadb"
        hostname: nextcloud-mariadb
        networks:
            - traefik_proxy
        volumes:
            - ./mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=keinerweisdas
            - MYSQL_PASSWORD=mysql
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    nextcloud-redis:
        image: redis:alpine
        restart: always
        container_name: nextcloud-redis
        networks:
            - traefik_proxy
        volumes:
            - ./redis:/data

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge