version: "3.6"
services:
    nextcloud:
        container_name: nextcloud
        restart: always
        # docker-compose exec nextcloud chown -R www-data:root /var/www
        #image: nextcloud:20.0.7-fpm-alpine
        image: registry.simon-haas.eu/nextcloud:21.0.0-fpm-alpine
        #build: ./fpm
        depends_on: 
            - nextcloud-mariadb
            - nextcloud-redis
        networks:
            - traefik_proxy
        environment:
            - REDIS_HOST=nextcloud-redis
        volumes:
            - ../nextcloud/data/nextcloud:/var/www/html
            #- ./fpm/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini
            - /var/run/clamav/clamd.ctl:/var/run/clamav/clamd.ctl
            - ../nextcloud/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

    web:
        #build: ./web
        image: registry.simon-haas.eu/nextcloud-nginx:alpine
        restart: always
        links:
            - nextcloud
        container_name: nextcloud-web
        volumes:
            - ../nextcloud/data/nextcloud:/var/www/html:ro
        #ports: 
        #    - 88:80
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=nextcloud"
            - "traefik.frontend.rule=Host:nextcloud.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"
            - traefik.frontend.headers.STSSeconds=315360000

    nextcloud-mariadb:
        image: mariadb
        container_name: "nextcloud-mariadb"
        hostname: nextcloud-mariadb
        networks:
            - traefik_proxy
        volumes:
            - ../nextcloud/data/mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=keinerweisdas
            - MYSQL_PASSWORD=mysql
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    nextcloud-redis:
        image: redis:alpine
        restart: always
        container_name: nextcloud-redis
        networks:
            - traefik_proxy
        volumes:
            - ../nextcloud/data/redis:/data

    onlyoffice:
        image: onlyoffice/documentserver
        container_name: onlyoffice
        restart: always
        networks: 
            - traefik_proxy
        labels:
            - "traefik.backend=onlyoffice"
            - "traefik.frontend.rule=Host:onlyoffice.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80" 

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge