version: "3.6"
services:
    nextcloud:
        container_name: nextcloud
        restart: always
        image: nextcloud:19.0.3
        networks:
            - traefik_proxy
        environment:
            - REDIS_HOST=nextcloud-redis
        volumes:
            - ./data:/var/www/html
        labels:
            - "traefik.backend=nextcloud"
            - "traefik.frontend.rule=Host:nextcloud.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=80"

    nextcloud-mariadb:
        image: mariadb
        container_name: "nextcloud-mariadb"
        hostname: nextcloud-mariadb
        networks:
            - traefik_proxy
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - target: 3306
              published: 3306
              protocol: tcp
              mode: host
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=keinerweisdas
            - MYSQL_PASSWORD=mysql
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    nextcloud-redis:
        image: redis:alpine
        restart: always
        container_name: nextcloud-redis
        networks:
            - traefik_proxy
        volumes:
            - ./redis:/data

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge