version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ../radarr/data/config:/config
      - ../radarr/data/movies:/movies #optional
      - ../radarr/data/downloads:/downloads #optional
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=radarr"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:radarr.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=7878"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge
