version: "3.6"
services:
    clarkson:
        image: linuxserver/clarkson
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_HOST=clarkson-mariadb
            - MYSQL_USERNAME=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - ENABLE_REGISTRATIONS=true
            - TZ=${TZ}
        container_name: clarkson
        restart: always
        networks: 
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.clarkson.loadbalancer.server.port=3000"
            - "traefik.http.routers.clarkson.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.clarkson.entrypoints=websecure"
            - "traefik.http.routers.clarkson.tls.certresolver=myresolver"

    clarkson-mariadb:
        image: mariadb
        container_name: clarkson-mariadb
        hostname: clarkson-mariadb
        networks: 
            - traefik
        volumes:
            - ./data/mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=clarkson
            - MYSQL_USER=${DB_USER}

networks:
    traefik:
        name: traefik