version: "3.6"
services:
    dolibarr:
        image: monogramm/docker-dolibarr
        volumes: 
            - ./data/html:/var/www/html
            - ./data/docs:/var/www/documents
        environment: 
            - DOLI_AUTO_CONFIGURE=''
        container_name: dolibarr
        security_opt:
        - no-new-privileges:true
        restart: always
        networks: 
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.dolibarr.loadbalancer.server.port=80"
            - "traefik.http.routers.dolibarr.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.dolibarr.entrypoints=websecure"
            - "traefik.http.routers.dolibarr.tls.certresolver=myresolver"

    dolibarr-mariadb:
        image: mariadb
        container_name: "dolibarr-mariadb"
        hostname: dolibarr-mariadb
        networks:
            - traefik
        volumes:
            - ./data/mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}

networks:
    traefik:
        name: traefik