version: "3.6"
services:
    gitlab:
        image: 'gitlab/gitlab-ce:13.2.9-ce.0'
        restart: always
        container_name: gitlab
        hostname: 'gitlab.simon-haas.eu'
        networks:
            - traefik_proxy
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://gitlab.simon-haas.eu'
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "gitlab"
                gitlab_rails['db_password'] = "gitlab"
                gitlab_rails['db_host'] = 'postgres'
                gitlab_rails['db_port'] = "5432"
                gitlab_rails['db_database'] = "gitlab"
                gitlab_rails['db_adapter'] = "postgresql"
                gitlab_rails['db_encoding'] = 'utf8'
                redis['enable'] = false
                gitlab_rails['redis_host'] = 'redis'
                gitlab_rails['redis_port'] = '6379'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
                nginx['listen_port'] = 443
                nginx['listen_https'] = false
                nginx['proxy_set_headers'] = {
                    'X-Forwarded-Proto' => 'https',
                    'X-Forwarded-Ssl' => 'on',
                    'Host' => 'gitlab.simon-haas.eu'
                }
        ports:
            - '2224:22'
        volumes:
            - './data/config:/etc/gitlab'
            - './data/logs:/var/log/gitlab'
            - './data/data:/var/opt/gitlab'
        labels:
            - "traefik.backend=gitlab"
            - "traefik.frontend.rule=Host:gitlab.simon-haas.eu"
            - "traefik.port=443"
            - "traefik.enable=true"
            - "traefik.frontend.entryPoints=https,http"
            # - "traefik.frontend.headers.SSLRedirect=true"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge