version: "3.6"
services:
    gitlab:
        image: 'gitlab/gitlab-ce:13.2.9-ce.0'
        restart: always
        container_name: gitlab
        hostname: 'gitlab.simon-haas.eu'
        depends_on:
            - redis
            - postgresql
        networks:
            - traefik_proxy
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://gitlab.simon-haas.eu'
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "gitlab"
                gitlab_rails['db_password'] = "password"
                gitlab_rails['db_host'] = 'postgresql'
                gitlab_rails['db_port'] = "5432"
                gitlab_rails['db_database'] = "gitlabhq_prod"
                gitlab_rails['db_adapter'] = "postgresql"
                gitlab_rails['db_encoding'] = 'utf8'
                redis['enable'] = false
                gitlab_rails['redis_host'] = 'redis'
                gitlab_rails['redis_port'] = '6379'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
                nginx['listen_port'] = 443
                nginx['listen_https'] = false
                nginx['proxy_set_headers'] = {
                    'X-Forwarded-Proto' => 'https',
                    'X-Forwarded-Ssl' => 'on',
                    'Host' => 'gitlab.simon-haas.eu'
                }
        ports:
            - '2224:22'
        volumes:
            - './gitlab/config:/etc/gitlab'
            - './gitlab/logs:/var/log/gitlab'
            - './gitlab/data:/var/opt/gitlab'
        labels:
            - "traefik.backend=gitlab"
            - "traefik.frontend.rule=Host:gitlab.simon-haas.eu"
            - "traefik.port=443"
            - "traefik.enable=true"
            - "traefik.frontend.entryPoints=https,http"
            # - "traefik.frontend.headers.SSLRedirect=true"

    postgresql:
        restart: always
        image: postgres:alpine
        #container_name: gitlab_postgresql
        environment:
            - POSTGRES_USER=gitlab
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=gitlabhq_prod
        volumes:
            - './postgresql/lib:/var/lib/postgresql'
            - './postgresql/data:/etc/postgresql'
            - './postgresql/log:/var/log/postgresql'
        networks:
            - traefik_proxy
    
    redis:
        restart: always
        image: redis:3-alpine
        #container_name: gitlab_redis
        volumes:
            - './redis/data:/data'
        networks:
            - traefik_proxy

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge