version: "3.6"
services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: homeserver
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    privileged: true
    command: /bin/sh -c "tailscaled && tailscale up --authkey=$KEY --advertise-exit-node --advertise-routes=$ROUTES"
