version: "2.4"
services:
  tailscale:
    privileged: true
    hostname: tailscale-homeserver
    network_mode: "host"
    image: tailscale/tailscale:latest
    volumes:
      - "/opt/appdata/tailscale/var_lib:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    environment:
      TS_AUTH_KEY:
      TS_ROUTES:
