version: "2.1"
services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
    #ports:
    #  - 9283:80
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=grocy"
      #- "traefik.protocol=http"
      - "traefik.frontend.rule=Host:grocy.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80" 

networks:
  traefik_proxy:
      external:
          name: traefik_proxy
  default:
      driver: bridge