version: "2.1"
services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
    ports:
      - 9283:80
    restart: always
    labels:
      - "traefik.backend=grocy"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:grocy.simon-haas.eu; PathPrefixStrip: /grocy"
      - "traefik.enable=true"
      - "traefik.port=80" 