version: '3.6'
services:
  trilium:
    image: zadam/trilium
    restart: always
    #ports:
    #  - "8080:8080"
    volumes:
      - ../trilium/data:/root/trilium-data
    restart: always
    container_name: trilium
    networks:
        - traefik_proxy
    labels:
        - "traefik.backend=trilium"
        - "traefik.frontend.rule=Host:trilium.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge
