version: '3.6'
services:
    storage:
        image: minio/minio
        ports:
          - 127.0.0.1:9000:9000
          #- 9001:9001
        environment:
          - MINIO_ROOT_USER=${STORE_ACCESS_KEY}
          - MINIO_ROOT_PASSWORD=${STORE_SECRET_KEY}
        entrypoint: sh
        command: -c 'mkdir -p /data/notea && /usr/bin/minio server /data --console-address ":9001"'
        volumes: 
            - ../notea/data:/data
        container_name: notea-storage
        restart: unless-stopped
        networks:
            - traefik_proxy

    app:
        image: cinwell/notea
        #ports:
        #    - 3000:3000
        environment: 
            - STORE_ACCESS_KEY=${STORE_ACCESS_KEY}
            - STORE_SECRET_KEY=${STORE_SECRET_KEY}
            - STORE_BUCKET=${STORE_BUCKET}
            - STORE_END_POINT=${STORE_END_POINT}
            - STORE_FORCE_PATH_STYLE=${STORE_FORCE_PATH_STYLE}
            - PASSWORD=${PASSWORD}
            - COOKIE_SECURE=${COOKIE_SECURE} # This is required on non-https sites
            - DISABLE_PASSWORD=false
        depends_on: 
            - storage
        container_name: notea-app
        restart: unless-stopped
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=notea"
            - "traefik.frontend.rule=Host:notea.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=3000"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge