version: '3.6'
services:
    storage:
        image: minio/minio
        ports:
          - 127.0.0.1:9000:9000
          - 9001:9001
        environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=minio123
        entrypoint: sh
        command: -c 'mkdir -p /data/notea && /usr/bin/minio server /data --console-address ":9001"'
        volumes: 
            - ../notea/data:/data
        container_name: notea-storage
        restart: unless-stopped
        networks:
            - traefik_proxy

    app:
        image: cinwell/notea
        ports:
            - 3000:3000
        environment: 
            - STORE_ACCESS_KEY=minio
            - STORE_SECRET_KEY=minio123
            - STORE_BUCKET=notea
            - STORE_END_POINT=http://storage:9000
            - STORE_FORCE_PATH_STYLE=true
            - PASSWORD=notea
            - COOKIE_SECURE=false # This is required on non-https sites
        depends_on: 
            - storage
        container_name: notea-app
        restart: unless-stopped
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=notea"
            - "traefik.frontend.rule=Host:notea.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=3000"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge