version: "3.6"
services:
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    environment:
      - JAVA_OPTS=-Dserver.use-forward-headers=true
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
      - ./data/music:/music
      - ./data/playlists:/playlists
      - ./data/podcasts:/podcasts
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.airsonic.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.airsonic.entrypoints: websecure
      traefik.http.services.airsonic.loadbalancer.server.port: 4040

networks:
  traefik:
    name: zone1
    external: true
