version: "3.6"
services:
    airsonic:
        image: lscr.io/linuxserver/airsonic-advanced
        environment:
            - JAVA_OPTS=-Dserver.use-forward-headers=true
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
        volumes:
            - ./data/config:/config
            - ./data/music:/music
            - ./data/playlists:/playlists
            - ./data/podcasts:/podcasts
        container_name: airsonic
        security_opt:
            - no-new-privileges:true
        restart: always
        networks: 
            - traefik
        labels:
            - custom.network=private
            - "traefik.enable=true"
            - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
            - "traefik.http.routers.airsonic.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.airsonic.entrypoints=websecure"
            - "traefik.http.routers.airsonic.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private