version: "3.6"
services:
  youtubedl:
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
    volumes:
      - ./data/appdata:/app/appdata
      - ./data/audio:/app/audio
      - ./data/video:/app/video
      - ./data/subscriptions:/app/subscriptions
      - ./data/users:/app/users
    image: tzahi12345/youtubedl-material:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.youtubedl.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.youtubedl.entrypoints: websecure
      traefik.http.services.youtubedl.loadbalancer.server.port: 17442

networks:
  traefik:
    name: zone1
