version: "3.6"
services:
  gogs:
    restart: always
    image: gogs/gogs:0.12.10
    ports:
      - "10022:22"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.gogs.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.gogs.entrypoints: websecure
      traefik.http.services.gogs.loadbalancer.server.port: 3000
      homepage.group: Media
      homepage.name: Gogs
      homepage.icon: gogs
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Git server

networks:
  traefik:
    name: zone1
