version: "3.6"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    container_name: prometheus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.prometheus.entrypoints: websecure
      traefik.http.services.prometheus.loadbalancer.server.port: 9090
      homepage.group: Infrastructure
      homepage.name: Prometheus
      homepage.icon: prometheus
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Collecting statistics

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - traefik

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0 # latest tag is not updated...
                                            # https://github.com/google/cadvisor/issues/3066    
                                            # To manual check versions: https://github.com/google/cadvisor/releases      
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    restart: unless-stopped
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.cadvisor.rule: Host(`${SUB_DOMAIN_CADVISOR}.${SERVER_DOMAIN}`)
      traefik.http.routers.cadvisor.entrypoints: websecure
      traefik.http.services.cadvisor.loadbalancer.server.port: 8080
      homepage.group: Infrastructure
      homepage.name: Cadvisor
      homepage.icon: cadvisor
      homepage.href: https://${SUB_DOMAIN_CADVISOR}.${SERVER_DOMAIN}
      homepage.description: Collecting statistics from docker containers

networks:
  traefik:
    name: zone1
