version: "3.6"
services:
    odoo:
        image: odoo:12.0
        networks:
            - traefik_proxy
        volumes:
            - ./data/data:/var/lib/odoo
            - ./data/config:/etc/odoo
            - ./data/addons:/mnt/extra-addons
        environment:
            - HOST=postgres
            - USER=odoo
            - PASSWORD=${POSTGRES_PASSWORD}
        labels:
            - "traefik.backend=odoo"
            - "traefik.frontend.rule=Host:odoo.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=8069"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge