version: "3.6"
services:
    web:
        image: odoo:13.0
        container_name: odoo
        restart: always
        networks:
            - traefik_proxy
        depends_on:
            - odoo-db
        environment:
            - HOST=mydb
            - USER=odoo
            - PASSWORD=myodoo
        volumes:
            - ./data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
        labels:
            - "traefik.backend=odoo"
            - "traefik.frontend.rule=Host:odoo.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=8069"

    odoo-db:
        image: postgres:10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=myodoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./odoo-db:/var/lib/postgresql/data/pgdata

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge