version: "3"

services:
  superset:
    image: apache/superset
    restart: unless-stopped
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.funnyservice.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.funnyservice.entrypoints: websecure
      traefik.http.services.funnyservice.loadbalancer.server.port: ${SERVICE_PORT}
      homepage.group: ${HOMEPAGE_GROUP}
      homepage.name: ${HOMEPAGE_NAME}
      homepage.icon: ${HOMEPAGE_ICON}
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: ${HOMEPAGE_DESCRIPTION}

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_DATABASE: superset
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  default:
    name: zone1
    external: true
