version: "3.6"
services:
    dyndns:
      image: tunix/digitalocean-dyndns
      container_name: dyndns
      restart: always
      environment:
        - DIGITALOCEAN_TOKEN=${DO_AUTH_TOKEN}
        - DOMAIN=${DOMAIN}
        - NAME=${DYNDNS_NAME}

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge