version: "3"

services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/config:/config
      - ./data/data:/data
    restart: always
    network_mode: container:gluetun # see ../gluetun/docker-compose.yml
    labels:
      homepage.group: Arr
      homepage.name: Mylar
      homepage.icon: mylar
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Comics
