version: "3.6"

services:
  traefik:
    restart: unless-stopped
    image: "traefik:2.8"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.storage=letsencrypt/acme.json"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_EMAIL}"
      #- "--certificatesResolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.dnsChallenge=true"
      - "--certificatesResolvers.myresolver.acme.dnschallenge.provider=${DNS_CHALLENGE_PROVIDER}"
      - "--certificatesResolvers.myresolver.acme.dnschallenge.resolvers=8.8.4.4:53,8.8.8.8:53"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=0"
      - --api.dashboard=true
      - --providers.docker.constraints=Label(`my.zone`, `zone1`)
      - --serverstransport.insecureskipverify=true

      - --api=true
      - --api.insecure=true
      # - --pilot.token=$TRAEFIK_PILOT_TOKEN
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v1.3.0
      # - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
      # - --entrypoints.http.address=:80
      # - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/letsencrypt:/letsencrypt
      - ./dynamic-config.yml:/etc/traefik/dynamic-config.yml
    env_file:
      - .env
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.domains[0].main: ${SERVER_DOMAIN}
      traefik.http.routers.traefik.tls.domains[0].sans: "*.${SERVER_DOMAIN}"
      traefik.http.routers.dashboard.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: myresolver
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: true
      traefik.http.routers.redirs.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.redirs.entrypoints: web
      traefik.http.routers.redirs.middlewares: redirect-to-https
      
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/verify?rd=https://login.${SERVER_DOMAIN}/
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: Remote-User, Remote-Groups, Remote-Name, Remote-Email

  authelia:
    image: ghcr.io/authelia/authelia
    container_name: authelia
    user: "1000:1000"
    volumes:
      - ./authelia:/config
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true 
      traefik.http.routers.authelia.rule: Host(`login.${SERVER_DOMAIN}`)
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=${TZ}

  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service
    command: 
      - --swarmMode=false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    container_name: ondemand
    labels:
      - my.zone=zone1
      - traefik.enable=true
      - traefik.http.services.ondemand.loadbalancer.server.port=10000

      - traefik.http.middlewares.ondemand-whoami.plugin.traefik-ondemand-plugin.name=whoami
      - traefik.http.middlewares.ondemand-whoami.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
      - traefik.http.middlewares.ondemand-whoami.plugin.traefik-ondemand-plugin.timeout=1m

      - traefik.http.middlewares.ondemand-traggo.plugin.traefik-ondemand-plugin.name=traggo
      - traefik.http.middlewares.ondemand-traggo.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
      - traefik.http.middlewares.ondemand-traggo.plugin.traefik-ondemand-plugin.timeout=1m

      # - traefik.http.middlewares.ondemand-wikijs.plugin.traefik-ondemand-plugin.names=[wikijs,wikijs_db]
      - traefik.http.middlewares.ondemand-wikijs.plugin.traefik-ondemand-plugin.names=wikijs,test
      - traefik.http.middlewares.ondemand-wikijs.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
      - traefik.http.middlewares.ondemand-wikijs.plugin.traefik-ondemand-plugin.timeout=1m
    networks:
      - traefik

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - my.zone=zone1
    networks:
      - traefik



  test:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    # logging:
    #   driver: "none"
    restart: unless-stopped
    volumes:
      - ./data-wikijs:/var/lib/postgresql/data
    container_name: test
    networks: 
        - traefik

  wikijs:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - test
    environment:
      DB_TYPE: postgres
      DB_HOST: test
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    container_name: wikijs
    security_opt:
        - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1



networks:
  traefik:
    name: zone1
