version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${PASSWORD} #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=${SUB_DOMAIN}.${SERVER_DOMAIN} #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./data:/config
    restart: unless-stopped
    networks:
        - traefik
    labels:
        my.zone: zone1
        traefik.enable: true
        traefik.http.routers.code-server.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
        traefik.http.routers.code-server.entrypoints: websecure
        traefik.http.services.code-server.loadbalancer.server.port: 8443

networks:
  traefik:
    name: zone1