version: "3.6"
services:
    portainer:
      image: portainer/portainer
      container_name: portainer
      restart: always
      networks:
        - traefik_proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ../portainer/data:/data
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=9000"
        
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge