version: "3.6"
services:
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        networks:
        - traefik_proxy
        labels:
        - "traefik.backend=adminer"
        - "traefik.frontend.rule=Host:adminer.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
    traefik_proxy:
        external:
        name: traefik_proxy
    default:
        driver: bridge