version: "3.6"

services:
  gitlab:
    restart: unless-stopped
    image: gitlab/gitlab-ce
    hostname: ${SUB_DOMAIN}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${SUB_DOMAIN}.${SERVER_DOMAIN}'
        gitlab_rails['lfs_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['proxy_set_headers'] = {
            "Host" => "$$http_host",
            "X-Real-IP" => "$$remote_addr",
            "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on"
        }

        registry_external_url 'http://${REGISTRY_SUB_DOMAIN}.${SERVER_DOMAIN}'
        registry['enable'] = true
        gitlab_rails['registry_enabled'] = true
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
            "Host" => "$$http_host",
            "X-Real-IP" => "$$remote_addr",
            "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on"
        }

        pages_external_url 'https://${PAGES_SUB_DOMAIN}.${SERVER_DOMAIN}'
        pages_nginx['enable'] = false
        gitlab_pages['external_http'] = ['0.0.0.0:8081']
        gitlab_pages['inplace_chroot'] = true
        gitlab_pages['enable'] = true
        gitlab_pages['internal_gitlab_server'] = "https://${SUB_DOMAIN}.${SERVER_DOMAIN}"
      # gitlab_pages['access_control'] = false # https://birkhoff.me/articles/deploying-gitlab-community-edition
    ports:
      - 2222:22
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.middlewares.gitlab-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gitlab.middlewares: gitlab-https-redirect
      traefik.http.services.gitlab.loadbalancer.server.port: 80
      traefik.http.routers.gitlab.tls: true
      traefik.http.routers.gitlab.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.gitlab.entrypoints: websecure
      traefik.http.routers.gitlab.service: gitlab

      traefik.http.routers.gitlab-registry.rule: Host(`${REGISTRY_SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.gitlab-registry.entrypoints: websecure
      traefik.http.routers.gitlab-registry.service: gitlab-registry
      traefik.http.services.gitlab-registry.loadbalancer.server.port: 5050

      traefik.http.services.gitlab-pages.loadbalancer.server.port: 8081
      traefik.http.routers.gitlab-pages.service: gitlab-pages
      traefik.http.routers.gitlab-pages.entrypoints: websecure
      traefik.http.routers.gitlab-pages.rule: Host(`${PAGES_SUB_DOMAIN}.${SERVER_DOMAIN}`) || HostRegexp(`{subdomain:[a-z]+}.${PAGES_SUB_DOMAIN}.${SERVER_DOMAIN}`)

      homepage.group: Media
      homepage.name: Gitlab
      homepage.icon: gitlab
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Git server
    volumes:
      - ./data/config:/etc/gitlab/
      - ./data/logs:/var/log/gitlab/
      - ./data/data:/var/opt/gitlab/
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true

networks:
  default:
    name: zone1
    external: true
