version: "3.6"
services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 3001:3001
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.uptimekuma.rule: Host(`uptimekuma.${SERVER_DOMAIN}`)
      traefik.http.routers.uptimekuma.entrypoints: websecure
      traefik.http.services.uptimekuma.loadbalancer.server.port: 3001
      homepage.group: Infrastructure
      homepage.name: Uptimekuma
      homepage.icon: uptime-kuma
      homepage.href: https://uptimekuma.${SERVER_DOMAIN}
      homepage.description: Monitoring tool

networks:
  traefik:
    name: zone1
    external: true
