version: "3.6"
services:
  nextcloud:
    container_name: nextcloud
    restart: always
    # docker-compose exec nextcloud chown -R www-data:root /var/www
    image: nextcloud:24.0.3-fpm
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    networks:
      - traefik
    environment:
      - REDIS_HOST=nextcloud-redis
    volumes:
      - ./data/nextcloud:/var/www/html

  cron:
    container_name: nextcloud-cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes_from:
      - nextcloud
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis

  web:
    image: nginx
    restart: always
    links:
      - nextcloud
    container_name: nextcloud-web
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      raefik.http.routers.nextcloud.entrypoints: websecure
      homepage.group: Media
      homepage.name: Nextcloud
      homepage.icon: emby.png
      homepage.href: http://emby.home/
      homepage.description: Nextcloud

  nextcloud-mariadb:
    image: mariadb:10.5
    container_name: "nextcloud-mariadb"
    hostname: nextcloud-mariadb
    networks:
      - traefik
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env

  nextcloud-redis:
    image: redis:alpine
    restart: always
    container_name: nextcloud-redis
    networks:
      - traefik
    volumes:
      - ./data/redis:/data

networks:
  traefik:
    name: zone1
