version: '3.3'
services:
  komga:
    image: gotson/komga
    volumes:
      - ./data/config:/config
      - ./data/data:/data
      - /etc/timezone:/etc/timezone:ro
    user: "1000:1000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.komga.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.komga.entrypoints: websecure
      traefik.http.services.komga.loadbalancer.server.port: 8080
      homepage.group: Media
      homepage.name: Komga
      homepage.icon: komga
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Comics

networks:
  traefik:
    name: zone1
    external: true
