version: '3.6'
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=${MYSQL_LOG_CONSOLE}
    volumes:
      - ./data/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik

  memcached:
    image: memcached:1.6
    entrypoint: memcached -m 256
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
          
  seafile:
    image: seafileltd/seafile-mc:latest
    volumes:
      - ./seafile.nginx.conf:/shared/nginx/conf/seafile.nginx.conf 
      - ./data/seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=${TZ}  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.${SERVER_DOMAIN} # Specifies your host name if https is enabled.
      # https://forum.seafile.com/t/cant-upload-download-files-with-android-client/4047/5
    depends_on:
      - db
      - memcached
    restart: unless-stopped
    ports:
      - 8002:8080
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.seafile.rule: Host(`seafile.${SERVER_DOMAIN}`)
      traefik.http.routers.seafile.entrypoints: websecure
      traefik.http.services.seafile.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: Seafile
      homepage.icon: seafile
      homepage.href: https://seafile.${SERVER_DOMAIN}
      homepage.description: File cloud

networks:
  traefik:
    name: zone1
    external: true
