version: "2.1"
services:
  hammond:
    image: akhilrex/hammond
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data/config:/config
      - ./data/assets:/assets
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.hammond.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.hammond.entrypoints: websecure
      traefik.http.services.hammond.loadbalancer.server.port: 3000
      homepage.group: Media
      homepage.name: Hammond
      homepage.icon: hammond
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: vehicle and expense management system

networks:
  traefik:
    name: zone1
