version: "3.6"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor  
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    restart: unless-stopped
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.cadvisor.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.cadvisor.entrypoints: websecure
      traefik.http.services.cadvisor.loadbalancer.server.port: 8080
      homepage.group: Infrastructure
      homepage.name: Cadvisor
      homepage.icon: cadvisor
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Collecting statistics from docker containers

networks:
  traefik:
    name: zone1
    external: true
