# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Media:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - DAS ist mein TEST:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
