# docker run --rm -d -e HLEDGER_JOURNAL_FILE=/data/all.journal -v "$HOME/journals:/data" -p 5000:5000 --user $(id --user) dastapov/hledger

version: "3.6"
services:
  hledger:
    image: dastapov/hledger
    user: "1000"
    environment:
      - HLEDGER_JOURNAL_FILE=/data/all.journal
      - HLEDGER_BASE_URL=https://hledger.${SERVER_DOMAIN}/
    volumes:
      - ./data:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.hledger.rule: Host(`hledger.${SERVER_DOMAIN}`)
      traefik.http.routers.hledger.entrypoints: websecure
      traefik.http.routers.hledger.middlewares: authelia@docker
      traefik.http.services.hledger.loadbalancer.server.port: 5000

networks:
  traefik:
    name: zone1
