version: "3.6"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-mate #choose your flavor
    container_name: webtop
    #privileged: true #optional but not needed unless you are running kde or i3 or other tools
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/config:/config #home directory
      #- /var/run/docker.sock:/var/run/docker.sock #optional only if you need access to docker winthin this container
    shm_size: "${RAM}gb" #optional but set to 1GB or higher to prevent browser crashes
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.webtop.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.webtop.entrypoints: websecure
      traefik.http.services.webtop.loadbalancer.server.port: 3000

networks:
  traefik:
    name: zone1