version: "3.6"
services:
  wger:
    container_name: wger
    image: wger/apache
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=wger"
      - "traefik.frontend.rule=Host:wger.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"
        
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge