version: "3.6"
services:
  wger:
    container_name: wger
    image: wger/apache
    volumes:
      - ./data/static:/home/wger/static
      - ./data/media:/home/wger/media
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=wger"
      - "traefik.frontend.rule=Host:wger.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache:
    restart: always
    image: redis:latest
    expose:
      - 6379
        
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge