version: "3"

services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./data/db:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .env:/app/.env
      - ./data/backups:/app/storage/app/backups
      # - ./data/logs:/app/storage/logs
      - linkace_logs:/app/storage/logs
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.linkace.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.linkace.entrypoints: websecure
      traefik.http.services.linkace.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: linkace
      homepage.icon: linkace
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: pocket alternative

networks:
  traefik:
    name: zone1
    external: true

volumes:
  linkace_logs:
    driver: local
