version: "3.6"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - CLI_ARGS=calibre-server
    volumes:
      - ./data/config:/config
    restart: unless-stopped
    security_opt:
        - seccomp:unconfined #optional
        - no-new-privileges:true
    networks:
        - traefik
    ports:
      - 8082:8080 # username: abc
      - 8081:8081
    # labels:
    #     my.zone: zone1
    #     traefik.enable: true
    #     traefik.http.routers.calibre.rule: Host(`calibre.${SERVER_DOMAIN}`)
    #     traefik.http.routers.calibre.entrypoints: websecure
    #     traefik.http.services.calibre.loadbalancer.server.port: 8080

    #     traefik.http.routers.calibre-w.rule: Host(`calibre-w.${SERVER_DOMAIN}`)
    #     traefik.http.routers.calibre-w.entrypoints: websecure
    #     traefik.http.services.calibre-w.loadbalancer.server.port: 8081

  calibre-web:
    image: linuxserver/calibre-web
    volumes:
      - ./data/config:/config
      - ./data/books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
        my.zone: zone1
        traefik.enable: true
        traefik.http.routers.calibre-web.rule: Host(`calibre-web.${SERVER_DOMAIN}`)
        traefik.http.routers.calibre-web.entrypoints: websecure
        traefik.http.services.calibre-web.loadbalancer.server.port: 8083

networks:
  traefik:
    name: zone1