version: "3.6"
services:
    clarkson:
        image: linuxserver/clarkson
        container_name: clarkson
        networks:
            - traefik_proxy
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_HOST=clarkson-mariadb
            - MYSQL_USERNAME=clarkson_user
            - MYSQL_PASSWORD=supersecretpassword
            - ENABLE_REGISTRATIONS=true
            - TZ=Europe/London
        restart: unless-stopped
        labels:
            - "traefik.backend=clarkson"
            - "traefik.frontend.rule=Host:clarkson.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=3000"

    clarkson-mariadb:
        image: mariadb
        container_name: "clarkson-mariadb"
        hostname: clarkson-mariadb
        networks:
            - traefik_proxy
        volumes:
            - ./mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=keinerweisdas
            - MYSQL_PASSWORD=supersecretpassword
            - MYSQL_DATABASE=clarkson
            - MYSQL_USER=clarkson_user

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge