version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${TRAGGO_DEFAULT_USER_NAME}
      TRAGGO_DEFAULT_USER_PASS: ${TRAGGO_DEFAULT_USER_PASS}
    volumes:
      - ./data:/opt/traggo/data
    container_name: traggo
    restart: always
    networks: 
        - traefik
    security_opt:
        - no-new-privileges:true
    labels:
        - traefik.zone=private
        - "traefik.enable=true"
        - "traefik.http.services.traggo.loadbalancer.server.port=3030"
        - "traefik.http.routers.traggo.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.traggo.entrypoints=websecure"
        - "traefik.http.routers.traggo.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private