version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    #ports:
    #  - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "mynewpassword"
    volumes:
      - ./data:/opt/traggo/data
    restart: always
    container_name: "traggo"
    networks:
        - traefik_proxy
    labels:
        - "traefik.backend=traggo"
        - "traefik.frontend.rule=Host:traggo.simon-haas.eu"
        - "traefik.enable=true"
        - "traefik.port=3030"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge