version: "3.6"
services:
  traggo:
    image: traggo/server:latest
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${TRAGGO_DEFAULT_USER_NAME}
      TRAGGO_DEFAULT_USER_PASS: ${TRAGGO_DEFAULT_USER_PASS}
    volumes:
      - ./data:/opt/traggo/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.traggo.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.traggo.entrypoints: websecure
      traefik.http.services.traggo.loadbalancer.server.port: 3030

networks:
  traefik:
    name: zone1
    external: true
