version: "3"

services:
  organizr:
    image: organizr/organizr
    volumes:
      #- ./data/config:/config
      - config:/config
    environment:
      PGID:
      PUID:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.organizr.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.organizr.entrypoints: websecure
      traefik.http.services.organizr.loadbalancer.server.port: ${SERVICE_PORT}
      homepage.group: ${HOMEPAGE_GROUP}
      homepage.name: ${HOMEPAGE_NAME}
      homepage.icon: ${HOMEPAGE_ICON}
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: ${HOMEPAGE_DESCRIPTION}

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example

networks:
  default:
    name: zone1
    external: true

volumes:
  config:
