version: '3.6'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    restart: always
    container_name: registry
    networks: 
        - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik