version: '3.6'
services:
    db:
        image: postgres:13.1
        volumes:
            - ../joplin/data/postgres:/var/lib/postgresql/data
        #ports:
        #    - "5432:5432"
        restart: unless-stopped
        networks:
            - traefik_proxy
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
        container_name: joplin-db

    app:
        image: joplin/server:2.1.1
        depends_on:
            - db
        #ports:
        #    - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            #- POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
        container_name: joplin-app
        networks:
            - traefik_proxy
        labels:
            - "traefik.backend=joplin"
            - "traefik.frontend.rule=Host:joplin.simon-haas.eu"
            - "traefik.enable=true"
            - "traefik.port=22300"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge