version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    container_name: heimdall
    restart: always
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
        - traefik.zone=private
        - "traefik.enable=true"
        - "traefik.http.services.heimdall.loadbalancer.server.port=80"
        - "traefik.http.routers.heimdall.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.heimdall.entrypoints=websecure"
        - "traefik.http.routers.heimdall.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private
