version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      TZ:
    volumes:
      - ./data:/var/cache/ntfy
      - ./server.yml:/etc/ntfy/server.yml
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.ntfy.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.services.ntfy.loadbalancer.server.port: 80
      homepage.group: Infrastructure
      homepage.name: ntfy
      homepage.icon: ntfy
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Notification Server

networks:
  traefik:
    name: zone1
