version: '3.5'

services:
    traefik:
        restart: always
        image: "traefik:2.6"
        container_name: traefik_public
        command:
            - "--log.level=DEBUG"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls.certResolver=myresolver"
            - "--certificatesresolvers.myresolver.acme.storage=letsencrypt/acme.json"
            - "--certificatesResolvers.myresolver.acme.email=${ACME_EMAIL}"
            - "--certificatesResolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            - "--certificatesResolvers.myresolver.acme.dnsChallenge=true"
            - "--certificatesResolvers.myresolver.acme.dnschallenge.provider=${DNS_CHALLENGE_PROVIDER}"
            - "--certificatesResolvers.myresolver.acme.dnschallenge.resolvers=8.8.4.4:53,8.8.8.8:53"
            - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=0"
            - --api.dashboard=true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - traefik_public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt:/letsencrypt
        env_file:
            - .env
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_public"
            - "traefik.http.routers.traefik.entrypoints=web"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.tls.domains[0].main=${SERVER_DOMAIN}"
            - "traefik.http.routers.traefik.tls.domains[0].sans=*.${SERVER_DOMAIN}"

            - "traefik.http.routers.traefik.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.traefik.tls.certresolver=myresolver"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=traefik-auth"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH}"

            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
            - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.redirs.entrypoints=web"
            - "traefik.http.routers.redirs.middlewares=redirect-to-https"

networks:
    traefik_public:
        name: traefik_public
