version: '3.7'

services:
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
