version: "3.6"

services:
  samba:
    command: '-s "media;/media/media;yes;no;no" -p'
    environment:
      - "NMBD=True"
      - "RECYCLE=False"
      - "USER=${USERNAME};${PASSWORD}"
    hostname: homeserver
    image: dperson/samba
    network_mode: host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - "./data/media:/media/media"
