# docker run -d --restart=unless-stopped -p 9090:80 -p 9091:443 --privileged -v /opt/rancher:/var/lib/rancher --name=rancher_docker_server rancher/rancher:latest

version: "3.6"
services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    volumes:
      - /opt/rancher:/var/lib/rancher
    security_opt:
      - no-new-privileges:true
    privileged: true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.rancher.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.rancher.entrypoints: websecure
      traefik.http.services.rancher.loadbalancer.server.port: 80
      homepage.group: Infrastructure
      homepage.name: Rancher
      homepage.icon: rancher
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Kubernetes-Manager

networks:
  traefik:
    name: zone1
