version: "3.6"
services:
  openproject:
    image: openproject/community:12
    volumes:
      - ./data/pgdata:/var/openproject/pgdata
      - ./data/assets:/var/openproject/assets
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SERVER_HOSTNAME=${SUB_DOMAIN}.${SERVER_DOMAIN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.openproject.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.openproject.entrypoints: websecure
      traefik.http.services.openproject.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1
    external: true
