version: "3.6"
services:
    openproject:
        container_name: openproject
        image: openproject/community:11
        restart: always
        networks:
          - traefik_proxy
        volumes:
          - ./data/pgdata:/var/openproject/pgdata
          - ./data/assets:/var/openproject/assets
        environment:
          - SECRET_KEY_BASE=6idLyBBe428Xg3HiVr74mOLx1zbgnk0Q
        labels:
          - "traefik.backend=openproject"
          - "traefik.frontend.rule=Host:openproject.simon-haas.eu"
          - "traefik.enable=true"
          - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge
        