version: '3.6'
services:
  ghost:
    image: ghost:4-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
    container_name: ghost
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
        my.zone: zone1
        traefik.enable: true
        traefik.http.routers.ghost.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
        traefik.http.routers.ghost.entrypoints: websecure

  db:
    container_name: ghost_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - traefik

networks:
    traefik:
        name: zone1