version: "3.6"
services:
    onlyoffice:
        image: onlyoffice/documentserver
        container_name: onlyoffice
        restart: always
        networks: 
            - traefik
        security_opt:
            - no-new-privileges:true
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
            - "traefik.http.routers.onlyoffice.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.onlyoffice.entrypoints=websecure"
            - "traefik.http.routers.onlyoffice.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik
