version: "2.1"
services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    container_name: grocy
    restart: always
    security_opt:
        - no-new-privileges:true
    networks:
        - traefik
    labels:
        - traefik.zone=private
        - "traefik.enable=true"
        - "traefik.http.services.grocy.loadbalancer.server.port=80"
        - "traefik.http.routers.grocy.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.grocy.entrypoints=websecure"
        - "traefik.http.routers.grocy.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private