version: "3.6"

services:
  php:
    image: serjs/go-socks5-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 1080:1080
    environment:
      PROXY_USER:
      PROXY_PASSWORD:
