# docker run -d --name socks5 -p 1080:1080 -e PROXY_USER=<PROXY_USER> -e PROXY_PASSWORD=<PROXY_PASSWORD> serjs/go-socks5-proxy

version: "3.6"

services:
  php:
    image: serjs/go-socks5-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 1080:1080
    environment:
      PROXY_USER: ${PROXY_USER}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
