version: "3"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ:
    volumes:
      - ./data/config:/config
      - ./data/data:/data
    restart: always
    network_mode: container:gluetun # see ../gluetun/docker-compose.yml
    labels:
      homepage.group: Arr
      homepage.name: Prowlarr
      homepage.icon: prowlarr
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Indexer
