version: '3'

services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    environment:
      BASE_URL: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      PASSWORD:
      TZ:
    volumes:
      - ./data/configs:/app/data/configs
      - ./data/icons:/app/public/icons
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.funnyservice.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.funnyservice.entrypoints: websecure
      traefik.http.services.funnyservice.loadbalancer.server.port: 7575
      homepage.group: ${HOMEPAGE_GROUP}
      homepage.name: ${HOMEPAGE_NAME}
      homepage.icon: ${HOMEPAGE_ICON}
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: ${HOMEPAGE_DESCRIPTION}

networks:
  default:
    name: zone1
    external: true
