version: "3"
services:
  pialert:
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: always
    volumes:
      - ./data/config:/home/pi/pialert/config
      - ./data/db:/home/pi/pialert/db
      - ./data/log:/home/pi/pialert/log
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_USER_GID=${HOST_USER_GID}