version: "3.6"
services:
  db-wger:
    image: postgres:12.0-alpine
    container_name: db-wger
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache-wger:
    container_name: cache-wger
    restart: always
    image: redis:latest
    expose:
      - 6379

  wger:
    image: wger/apache
    volumes:
      - ./data/static:/home/wger/static
      - ./data/media:/home/wger/media
    env_file:
      - .env
    depends_on:
      - db-wger
      - cache-wger
    container_name: wger
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.wger.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.wger.entrypoints: websecure
      traefik.http.services.syncthing.loadbalancer.server.port: 80

networks:
  traefik:
    name: zone1
