version: "3.6"
services:
  pihole:
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - './data/etc-pihole:/etc/pihole'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.pihole.entrypoints: websecure
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.routers.pihole.middlewares: "pihole-admin"
      traefik.http.middlewares.pihole-admin.addprefix.prefix: "/admin"
      homepage.group: Infrastructure
      homepage.name: Pihole
      homepage.icon: pihole
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.descriptioon: DNS server
      homepage.widget.type: pihole
      homepage.widget.url: https://${SUB_DOMAIN}.${SERVER_DOMAIN}/
      homepage.widget.proxy: false
      
networks:
  traefik:
    name: zone1
    external: true
