version: "3.6"
services:
    librespeed:
        image: adolfintel/speedtest
        container_name: librespeed
        restart: always
        security_opt:
            - no-new-privileges:true
        networks:
            - traefik
        labels:
            my.zone: zone1
            traefik.enable: true
            traefik.http.routers.librespeed.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
            traefik.http.routers.librespeed.entrypoints: websecure

networks:
    traefik:
        name: zone1