version: "3.6"
services:
    librespeed:
        image: adolfintel/speedtest
        container_name: librespeed
        restart: always
        security_opt:
            - no-new-privileges:true
        networks:
            - traefik
        labels:
            - custom.network=private
            - "traefik.enable=true"
            - "traefik.http.services.librespeed.loadbalancer.server.port=80"
            - "traefik.http.routers.librespeed.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
            - "traefik.http.routers.librespeed.entrypoints=websecure"
            - "traefik.http.routers.librespeed.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik_private