version: "3.6"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERURL=${SERVERURL} #optional
      - SERVERPORT=51820 #optional
      - PEERS=${PEERS} #optional
      #- PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
      #- ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
    volumes:
      - ./data/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    #sysctls:
    #  - net.ipv4.conf.all.src_valid_mark=1
    restart: always