---
version: "3.7"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ:
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.mealie.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.services.mealie.loadbalancer.server.port: 9000
      homepage.group: Media
      homepage.name: mealie
      homepage.icon: mealie
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: recipe manager and meal planner
      
networks:
  traefik:
    name: zone1
    external: true
