version: "3.6"

services:
  app:
    image: monica:3.2.0
    container_name: monica-app
    depends_on:
      - db
    environment:
      - APP_KEY=base64:L2TswbK1KXdP+eHHuiPNf9IcvyZj8Nx+qCBfwJevP18=
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ../monica/data/app:/var/www/html/storage
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=monica"
      - "traefik.frontend.rule=Host:monica.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"

  db:
    image: mysql:5.7
    container_name: monica-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - ../monica/data/mysql:/var/lib/mysql
    restart: always
    networks:
      - traefik_proxy

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge