TODO database.db file must already exist (script to create it?)
version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.17.2
    user: 0:0
    volumes:
      - ..:/srv
      - ./data/filebrowser.db:/database.db
    security_opt:
      - no-new-privileges:true
    container_name: filebrowser
    restart: always
    networks: 
        - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
        - "traefik.http.routers.filebrowser.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)"
        - "traefik.http.routers.filebrowser.entrypoints=websecure"
        - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"

networks:
    traefik:
        name: traefik