version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.17.2
    container_name: filebrowser
    user: 0:0
    #ports:
    #  - 8081:80
    volumes:
      - ..:/srv
      - ../filebrowser/filebrowser.db:/database.db # file must already exist
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=filebrowser"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:filebrowser.simon-haas.eu"
      - "traefik.enable=true"
      - "traefik.port=80"

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        driver: bridge