version: "3.4"
services:
  netbox: &netbox
    image: netboxcommunity/netbox:${VERSION-v3.3-2.3.0}
    depends_on:
      - postgres
      - redis
      - redis-cache
      - netbox-worker
    env_file: .env
    user: "unit:root"
    volumes:
      - ./data/configuration:/etc/netbox/config:z,ro
      - ./data/reports:/etc/netbox/reports:z,ro
      - ./data/scripts:/etc/netbox/scripts:z,ro
      - ./data/media:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
      - redis
      - postgres
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      - redis
      - postgres
    command:
      - /opt/netbox/housekeeping.sh

  # postgres
  postgres:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: .env
    volumes:
      - ./data/redis:/data

  redis-cache:
    image: redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: .env
    volumes:
      - ./data/redis-cache:/data
