version: "2"

services:
  remark:
    image: umputun/remark42:latest
    hostname: "remark42"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - ./data:/srv/var
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.remark.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.remark.entrypoints: websecure
      traefik.http.services.remark.loadbalancer.server.port: 8080
      homepage.group: Infrastructure
      homepage.name: remark42
      homepage.icon: reamrk
      homepage.href: https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      homepage.description: Comments for static sites

networks:
  traefik:
    name: zone1
    external: true
